/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.GasFornecedor;
import bean.GasTipo;
import bean.GasCompra;
import bean.GasCompraProduto;
import bean.GasProduto;
import dao.CompraDAO;
import dao.TipoDAO;
import dao.FornecedorDAO;
import dao.CompraProdutoDAO;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import jdk.nashorn.internal.scripts.JS;
import tools.Util;

/**
 *
 * @author geova
 */
public class JDlgCompra extends javax.swing.JDialog {

    /**
     * Creates new form JDlgCompra
     */
    MaskFormatter mascaraDataCompra;
    public CompraDAO compraDAO;
    public CompraProdutoDAO compraProdutoDAO;
    public CompraProdutosControler compraProdutosControler;
    boolean incluindo;
    public GasCompra gasCompra;

    public JDlgCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Compra");
        habilitar(false);
        compraDAO = new CompraDAO();
        TipoDAO tipoDAO = new TipoDAO();
        compraProdutoDAO = new CompraProdutoDAO();
        List listaTipo = tipoDAO.listALL();
        for (int i = 0; i < listaTipo.size(); i++) {
            jCboTipo.addItem((GasTipo) listaTipo.get(i));
        }
        FornecedorDAO fornecedorDAO = new FornecedorDAO();
        List listaFornecedor = fornecedorDAO.listALL();
        for (int i = 0; i < listaFornecedor.size(); i++) {
            jCboFornecedor.addItem((GasFornecedor) listaFornecedor.get(i));
        }
        List lista = new ArrayList();
        compraProdutosControler = new CompraProdutosControler();
        compraProdutosControler.setList(lista);
        jTable.setModel(compraProdutosControler);
        try {
            mascaraDataCompra = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFmtDataCompra.setFormatterFactory(new DefaultFormatterFactory(mascaraDataCompra));
    }

    public void habilitar(boolean valor) {
        Util.habilitar(valor, jTxtCodigo, jFmtDataCompra, jCboFornecedor, jCboTipo, jTxtTotal, jBtnConfirmar, jBtnCancelar, jTxtFormaDePagamento, jTable);
        Util.habilitar(valor, jBtnIncluirP, jBtnExcluirP, jBtnAlterarP);
        Util.habilitar(!valor, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
    }

    public GasCompra viewBean() {
        GasCompra gasCompra = new GasCompra();
        gasCompra.setGasIdCompra(Util.strInt(jTxtCodigo.getText()));
        gasCompra.setGasDataCompra(Util.strDate(jFmtDataCompra.getText()));
        gasCompra.setGasFornecedor((GasFornecedor) jCboFornecedor.getSelectedItem());
        gasCompra.setGasTipo((GasTipo) jCboTipo.getSelectedItem());
        gasCompra.setGasTotal(Util.strDouble(jTxtTotal.getText()));
        gasCompra.setGasFormaDePagamento(jTxtFormaDePagamento.getText());
        return gasCompra;
    }

    public void beanView(GasCompra gasCompra) {
        jTxtCodigo.setText(Util.intStr(gasCompra.getGasIdCompra()));
        jFmtDataCompra.setText(Util.dateStr(gasCompra.getGasDataCompra()));
        jCboFornecedor.setSelectedItem(gasCompra.getGasFornecedor());
        jCboTipo.setSelectedItem(gasCompra.getGasTipo());
        jTxtTotal.setText(String.valueOf(gasCompra.getGasTotal()));
        jTxtFormaDePagamento.setText(gasCompra.getGasFormaDePagamento());

        compraProdutoDAO = new CompraProdutoDAO();
        List listaProd = (List) compraProdutoDAO.listaProduto(gasCompra);
        compraProdutosControler.setList(listaProd);
    }

    public int getSelectedRowProd() {
        return jTable.getSelectedRow();
    }

//     public void DeleteLinha() {
//         GasCompraProduto gasCompraProduto = new GasCompraProduto();
//         for (int vez = 0; vez < gasCompraProduto.getGasCompra(); vez++) {   
//                    compraProdutoDAO.delete(gasCompraProduto.getGasCompra());
//                }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCboTipo = new javax.swing.JComboBox<GasTipo>();
        jCboFornecedor = new javax.swing.JComboBox<GasFornecedor>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBtnCancelar = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnIncluir = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnExcluirP = new javax.swing.JButton();
        jBtnAlterarP = new javax.swing.JButton();
        jBtnIncluirP = new javax.swing.JButton();
        jFmtDataCompra = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtFormaDePagamento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        jLabel1.setText("codigo");

        jLabel2.setText("Data da Compra");

        jTxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTotalActionPerformed(evt);
            }
        });

        jLabel5.setText("Total");

        jCboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboTipoActionPerformed(evt);
            }
        });

        jLabel6.setText("Fornecedor");

        jLabel7.setText("Tipo");

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gravar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnExcluirP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluirP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirPActionPerformed(evt);
            }
        });

        jBtnAlterarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnAlterarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarPActionPerformed(evt);
            }
        });

        jBtnIncluirP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluirP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirPActionPerformed(evt);
            }
        });

        jLabel3.setText("Forma de Pagamento");

        jTxtFormaDePagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFormaDePagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnAlterarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnIncluirP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnExcluirP, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFmtDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jCboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jCboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTxtFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(199, 199, 199))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluirP, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluirP, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterarP, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTotalActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTxtTotalActionPerformed

    private void jCboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboTipoActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
        Util.limparCampos(jTxtCodigo, jFmtDataCompra, jCboFornecedor, jCboTipo, jTxtTotal, jTxtFormaDePagamento);
        compraProdutosControler.setList(new ArrayList());
        gasCompra = null;
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        gasCompra = viewBean();
        if (incluindo == true) {
            compraDAO.insert(gasCompra);
            GasCompraProduto gasCompraProduto;
            for (int linha = 0; linha < jTable.getRowCount(); linha++) {
                gasCompraProduto = compraProdutosControler.getbean(linha);
                gasCompraProduto.setGasCompra(gasCompra);
                compraProdutoDAO.insert(gasCompraProduto);
            }
        } else {
            compraDAO.update(gasCompra);
            GasCompraProduto gasCompraProduto;
            Object object = compraDAO.Buscar(Util.strInt(jTxtCodigo.getText()));
            compraProdutoDAO.deletefk((GasCompra) object);
            //  Object buscar = compraDAO.Buscar(Util.strInt(jTxtCodigo.getText()));
            //  Object fk =  Util.strInt(jTxtCodigo.getText());
            // int fk = Util.strInt(jTxtCodigo.getText());
            // compraProdutoDAO.deleteFk(fk);
//remover todos os pedidos produtos deste pedido
            // jTable.setModel(compraProdutosControler);
            //incluir todos os pedidosProduto que estao no jtable
            for (int linha = 0; linha < jTable.getRowCount(); linha++) {
                gasCompraProduto = compraProdutosControler.getbean(linha);
                gasCompraProduto.setGasCompra(gasCompra);
                compraProdutoDAO.insert(gasCompraProduto);
            }
        }
        habilitar(false);
        Util.limparCampos(jTxtCodigo, jFmtDataCompra, jCboTipo, jCboFornecedor, jTxtTotal, jTxtFormaDePagamento);
        compraProdutosControler.setList(new ArrayList());

        gasCompra = null;
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (gasCompra != null) {
            if (Util.pergunta("Deseja excluir o pedido ?") == true) {
                compraProdutoDAO = new CompraProdutoDAO();
            //    GasCompraProduto gasCompraProduto;
                Object object = compraDAO.Buscar(Util.strInt(jTxtCodigo.getText()));
                compraProdutoDAO.deletefk((GasCompra) object);
                // for (int linha = 0; linha < jTable.getRowCount(); linha++) {
                //   gasCompraProduto = compraProdutosControler.getbean(linha);
                // compraProdutoDAO.delete(gasCompraProduto);
                //  }
                gasCompra = viewBean();
                compraDAO.delete(gasCompra);
            }
        } else {
            Util.mensagem("Deve ser realizada uma pesquisa antes");
        }
        Util.limparCampos(jTxtCodigo, jFmtDataCompra, jCboFornecedor, jCboTipo, jTxtTotal, jTxtFormaDePagamento);
        List lista = new ArrayList();
        compraProdutosControler.setList(lista);
        jTable.setModel(compraProdutosControler);
        gasCompra = null;
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        if (gasCompra != null) {
            habilitar(true);
            incluindo = false;
        } else {
            Util.mensagem("Deve ser realizada uma pesquisa antes");
        }
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.limparCampos(jTxtCodigo, jFmtDataCompra, jCboFornecedor, jCboTipo, jTxtTotal, jTxtFormaDePagamento);
        habilitar(true);
        compraProdutosControler.setList(new ArrayList());
        jTxtCodigo.grabFocus();
        incluindo = true;
        gasCompra = new GasCompra();
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        JDlgCompraPesquisar jDlgCompraPesquisar = new JDlgCompraPesquisar(null, true);
        jDlgCompraPesquisar.setTelaAnterior(this);
        jDlgCompraPesquisar.setVisible(true);
        gasCompra = new GasCompra();

    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnExcluirPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirPActionPerformed
        int linha = jTable.getSelectedRow();
        if (linha == -1) {
            Util.mensagem("Nenhuma linha selecionada");
        } else {
            if (Util.pergunta("Confirma exclusão do produto?") == true) {
                compraProdutosControler.removeBean(linha);
            }
        }

    }//GEN-LAST:event_jBtnExcluirPActionPerformed

    private void jBtnAlterarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarPActionPerformed
        JDlgCompraProdutosIA jDlgCompraProdutosIA = new JDlgCompraProdutosIA(null, true);
        jDlgCompraProdutosIA.setTitle("Alteração de produtos");
        jDlgCompraProdutosIA.setTelaAnterior(this);
        int linSel = jTable.getSelectedRow();
        GasCompraProduto gasCompraProduto = (GasCompraProduto) compraProdutosControler.getbean(linSel);
        jDlgCompraProdutosIA.beanView(gasCompraProduto);
        jDlgCompraProdutosIA.setVisible(true);


    }//GEN-LAST:event_jBtnAlterarPActionPerformed

    private void jBtnIncluirPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirPActionPerformed
        JDlgCompraProdutosIA jDlgCompraProdutosIA = new JDlgCompraProdutosIA(null, true);
        jDlgCompraProdutosIA.setTitle("Inclusão de produtos");
        jDlgCompraProdutosIA.setTelaAnterior(this);
        jDlgCompraProdutosIA.setVisible(true);
    }//GEN-LAST:event_jBtnIncluirPActionPerformed

    private void jTxtFormaDePagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFormaDePagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFormaDePagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgCompra dialog = new JDlgCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnAlterarP;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnExcluirP;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnIncluirP;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<GasFornecedor> jCboFornecedor;
    private javax.swing.JComboBox<GasTipo> jCboTipo;
    private javax.swing.JFormattedTextField jFmtDataCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtFormaDePagamento;
    private javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables
}
