package bean;
// Generated 04/12/2023 10:11:15 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GasCompra generated by hbm2java
 */
@Entity
@Table(name="gas_compra"
    ,catalog="db_geovane_silva"
)
public class GasCompra  implements java.io.Serializable {


     private int gasIdCompra;
     private GasFornecedor gasFornecedor;
     private GasTipo gasTipo;
     private Date gasDataCompra;
     private double gasTotal;
     private String gasFormaDePagamento;

    public GasCompra() {
    }

	
    public GasCompra(int gasIdCompra, GasFornecedor gasFornecedor, GasTipo gasTipo) {
        this.gasIdCompra = gasIdCompra;
        this.gasFornecedor = gasFornecedor;
        this.gasTipo = gasTipo;
    }
    public GasCompra(int gasIdCompra, GasFornecedor gasFornecedor, GasTipo gasTipo, Date gasDataCompra, double gasTotal, String gasFormaDePagamento) {
       this.gasIdCompra = gasIdCompra;
       this.gasFornecedor = gasFornecedor;
       this.gasTipo = gasTipo;
       this.gasDataCompra = gasDataCompra;
       this.gasTotal = gasTotal;
       this.gasFormaDePagamento = gasFormaDePagamento;
    }
   
     @Id 

    
    @Column(name="gas_id_compra", unique=true, nullable=false)
    public int getGasIdCompra() {
        return this.gasIdCompra;
    }
    
    public void setGasIdCompra(int gasIdCompra) {
        this.gasIdCompra = gasIdCompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gas_fk_fornecedor", nullable=false)
    public GasFornecedor getGasFornecedor() {
        return this.gasFornecedor;
    }
    
    public void setGasFornecedor(GasFornecedor gasFornecedor) {
        this.gasFornecedor = gasFornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gas_fk_tipo", nullable=false)
    public GasTipo getGasTipo() {
        return this.gasTipo;
    }
    
    public void setGasTipo(GasTipo gasTipo) {
        this.gasTipo = gasTipo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gas_data_compra", length=10)
    public Date getGasDataCompra() {
        return this.gasDataCompra;
    }
    
    public void setGasDataCompra(Date gasDataCompra) {
        this.gasDataCompra = gasDataCompra;
    }

    
    @Column(name="gas_total", precision=10)
    public double getGasTotal() {
        return this.gasTotal;
    }
    
    public void setGasTotal(double gasTotal) {
        this.gasTotal = gasTotal;
    }

    
    @Column(name="gas_forma_de_pagamento", length=45)
    public String getGasFormaDePagamento() {
        return this.gasFormaDePagamento;
    }
    
    public void setGasFormaDePagamento(String gasFormaDePagamento) {
        this.gasFormaDePagamento = gasFormaDePagamento;
    }





}


